/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-07-20 09:33:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.*;
import java.sql.*;

public final class Candidate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Buttons.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Profile.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Tables.css\">\r\n");
      out.write("\r\n");
      out.write("<script >\r\n");
      out.write("function applyForJob(id){\r\n");
      out.write("\tdocument.getElementById(id).disabled = true;\r\n");
      out.write("\txmlHttp=GetXmlHttpObject()\r\n");
      out.write("\tvar url=\"ApplyForJob.jsp\";\r\n");
      out.write("\turl=url+\"?id=\"+id;\r\n");
      out.write("\txmlHttp.onreadystatechange=stateChanged()\r\n");
      out.write("\txmlHttp.open(\"GET\",url,true)\r\n");
      out.write("\txmlHttp.send(null)\r\n");
      out.write("\tlocation.href=\"Candidate.jsp\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function undo(id){\r\n");
      out.write("\tvar id1 = -(id);\r\n");
      out.write("\tdocument.getElementById(id).disabled = true;\r\n");
      out.write("\tdocument.getElementById(id1).disabled = false;\r\n");
      out.write("\txmlHttp=GetXmlHttpObject()\r\n");
      out.write("\tvar url=\"UndoApplication.jsp\";\r\n");
      out.write("\turl=url+\"?id=\"+id1;\r\n");
      out.write("\txmlHttp.onreadystatechange=stateChanged(id)\r\n");
      out.write("\txmlHttp.open(\"GET\",url,true)\r\n");
      out.write("\txmlHttp.send(null)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function stateChanged(){ \r\n");
      out.write("\tif(xmlHttp.readyState==4 || xmlHttp.readyState==\"complete\"){\r\n");
      out.write("\t\tvar showdata = xmlHttp.responseText; \r\n");
      out.write("\t\talert(showdata)\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function GetXmlHttpObject(){\r\n");
      out.write("\tvar xmlHttp=null;\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\txmlHttp=new XMLHttpRequest();\r\n");
      out.write("\t}\r\n");
      out.write("\tcatch (e) {\r\n");
      out.write("\t\ttry {\r\n");
      out.write("\t\t\txmlHttp=new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\tcatch (e){\r\n");
      out.write("\t\txmlHttp=new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn xmlHttp;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction RegValidator()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar email1 = document.CandidateProfile.email.value;\r\n");
      out.write("\t\tvar fname1 = document.CandidateProfile.fname.value;\r\n");
      out.write("\t\tvar lname1 = document.CandidateProfile.lname.value;\r\n");
      out.write("\t\tvar sex1 = document.CandidateProfile.sex.value;\r\n");
      out.write("\t\tvar dob1 = document.CandidateProfile.dob.value;\r\n");
      out.write("\t\tvar address1 = document.CandidateProfile.address.value;\r\n");
      out.write("\t\tvar pincode1 = document.CandidateProfile.pincode.value;\r\n");
      out.write("\t\tvar phone1 = document.CandidateProfile.phone.value;\r\n");
      out.write("\t\tvar exp1 = document.CandidateProfile.exp.value;\r\n");
      out.write("\t\tvar degree1 = document.CandidateProfile.degree.value;\r\n");
      out.write("\t\tvar stream1 = document.CandidateProfile.stream.value;\r\n");
      out.write("\t\tvar validemail = /[a-zA-Z0-9._-]+[@]{1}[a-z]+[.]{1}[a-zA-Z]{3}$/;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(email1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter email\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!(validemail.test(email1)))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"email not correct\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(fname1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter fname\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(lname1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter lname\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(sex1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter sex\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(dob1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter dob\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(address1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter address\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(pincode1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter pincode\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(phone1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter phone\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(exp1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter exp\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(degree1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter degree\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(stream1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter stream\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.welcome{\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\theight: 100px;\r\n");
      out.write("\t\twidth: auto;\r\n");
      out.write("\t\tbackground-color: inherit;\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tpadding-right: 35px;\t\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 	
	Connection con = null;
	PreparedStatement ps = null;
	ResultSet rs = null;
	
	try{
		Class.forName("com.mysql.jdbc.Driver");
		con = DriverManager.getConnection("jdbc:mysql://localhost:3306/GlobsynST17ProjectDB", "abhishekp03", "d!ve!nnow");
	}
	catch(Exception e){
		e.printStackTrace();
	}
	
	int status=-1;
	HttpSession session3 = request.getSession(false);
	Object ob = session3.getAttribute("key");
	Object ob2 = session3.getAttribute("key2");
	String email = ob.toString();
	String foo = ob2.toString();
	status = Integer.parseInt(foo);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\" >\r\n");
      out.write("\t<img class=\"center\" src=\"Images/JobsPikr.png\">\r\n");
      out.write("\t<div class=\"welcome\">\r\n");
      out.write("\t\t<p><font color=\"white\"><br>Welcome<br>");
      out.print(email);
      out.write("</font></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"tab\">\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Home')\" id=\"default\">Home</button>\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Edit Profile')\">Edit Profile</button>\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'My Applications')\">My Applications</button>\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Change Password')\">Change Password</button>\r\n");
      out.write("  <form action=\"Logout\" method=\"post\">\r\n");
      out.write("  \t<button class=\"tablinks\">Logout</button>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Home\" class=\"tabcontent\">\r\n");
 
	if(status==0){

      out.write("\r\n");
      out.write("\t<h3>Welcome</h3>\r\n");
      out.write("\t<h3>You have been successfully register</h3>\r\n");
      out.write("\t<p>Create your profile first</p>\r\n");
      out.write("\t<input type=\"button\" onclick=\"openTab(event, 'Edit Profile')\" value=\"Create Profile\">\r\n");
 
	}
	else{
		int job_id = 0;
		String name = null;
		String post = null;
		String location = null;
		String salary = null;
		String exp = null;
		String description = null;
		
		try{
			ps = con.prepareStatement("SELECT j.job_id, r.name, j.post, j.location, j.salary, j.exp, j.description FROM joblist j, recruiterProfile r WHERE j.email=r.email;");
			rs = ps.executeQuery();

			while(rs.next()){
				job_id = rs.getInt("j.job_id");
				name = rs.getString("r.name");
				post = rs.getString("j.post");
				location = rs.getString("j.location");
				salary = rs.getString("j.salary");
				exp = rs.getString("j.exp");
				description = rs.getString("j.description"); 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<h3 align=\"center\">Job #ID: ");
      out.print(job_id);
      out.write("</h3>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table class=\"table1\" align=\"center\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<th class=\"th1\">Particulars</th>\r\n");
      out.write("\t\t\t\t\t<th class=\"th1\">Details</th>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr class=\"tr1\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td1\">Organization</td>\r\n");
      out.write("\t\t\t \t\t<td class=\"td1\">");
      out.print(name);
      out.write("</td>\r\n");
      out.write("\t\t\t \t</tr>\r\n");
      out.write("\t\t\t \t<tr class=\"tr1\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td1\">Designation</td>\r\n");
      out.write("\t\t\t \t\t<td class=\"td1\">");
      out.print(post);
      out.write("</td>\r\n");
      out.write("\t\t\t \t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"tr1\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td1\">Location</td>\r\n");
      out.write("\t\t\t \t\t<td class=\"td1\">");
      out.print(location);
      out.write("</td>\r\n");
      out.write("\t\t\t \t</tr>\r\n");
      out.write("\t\t\t\t<tr class=\"tr1\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td1\">Salary</td>\r\n");
      out.write("\t\t\t \t\t<td class=\"td1\">");
      out.print(salary);
      out.write("</td>\r\n");
      out.write("\t\t\t \t</tr>\r\n");
      out.write("\t\t\t \t<tr class=\"tr1\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td1\">Experience</td>\r\n");
      out.write("\t\t\t \t\t<td class=\"td1\">");
      out.print(exp);
      out.write("</td>\r\n");
      out.write("\t\t\t\t </tr>\r\n");
      out.write("\t\t\t\t <tr class=\"tr1\">\r\n");
      out.write("\t\t\t\t\t<td class=\"td1\">Job Description</td>\r\n");
      out.write("\t\t\t\t \t<td class=\"td1\">");
      out.print(description);
      out.write("</td>\r\n");
      out.write("\t\t\t\t </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\t\r\n");
      out.write("\t\t<input type=\"button\" id=\"");
      out.print( job_id );
      out.write("\" class=\"apply\" value=\"Apply\" onclick=\"applyForJob(this.id);\">\r\n");
      out.write("\t\t<br><br>\t\t\t\t\r\n");
 
			}
		}
		catch(Exception e){
			e.printStackTrace();
		}
	} 

      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"Edit Profile\" class=\"tabcontent\" align=\"center\">\r\n");
      out.write("\t<br><br>\r\n");
      out.write("\t<div id=\"picture\">\r\n");
      out.write("\t\t<img src=\"Images/NoImage.jpg\" /><br><br>\r\n");
      out.write("\t\t<form action=\"UploadPicture\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<input name=\"photo\" type=\"file\" />&emsp;\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"Change Picture\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div><br><br>\r\n");
      out.write("\t\r\n");
	
	String fname = "";
	String lname = "";
	String sex = "";
	String dob = "";
	String address = "";
	String pincode = "";
	String phone = "";
	String exp = "";
	String degree = "";
	String stream = "";

	if(status!=0){
		try{
			ps = con.prepareStatement("SELECT fname, lname, sex, dob, address, pincode, phone, exp, degree, stream FROM candidateProfile WHERE email=?;");
			ps.setString(1, email);
			rs=ps.executeQuery();
			while(rs.next()){
				fname = rs.getString("fname");
				lname = rs.getString("lname");
				sex = rs.getString("sex");
				dob = rs.getString("dob");
				address = rs.getString("address");
				pincode = Long.toString(rs.getLong("pincode"));
				phone = Long.toString(rs.getLong("phone"));
				exp = rs.getString("exp");
				degree = rs.getString("degree");
				stream = rs.getString("stream");;
			}
			rs = ps.executeQuery();
		}
		catch(Exception e){
			e.printStackTrace();
		}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"CandidateProfile\" action=\"UpdateCandidateServlet\" method=\"post\" onsubmit=\"return RegValidator();\">\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("\t<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t      <td>E-mail</td>\r\n");
      out.write("\t\t      <td><input type=\"text\" name=\"email\"  value=\"");
      out.print( email );
      out.write("\" readonly></td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t        \r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t      <td>First name</td>\r\n");
      out.write("\t\t      <td><input type=\"text\" name=\"fname\" value=\"");
      out.print( fname );
      out.write("\"></td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t      <td>Last name</td>\r\n");
      out.write("\t\t      <td><input type=\"text\" name=\"lname\" value=\"");
      out.print( lname );
      out.write("\"></td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t        \r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t      <td>Gender</td>\r\n");
      out.write("\t\t      <td><input type=\"text\" name=\"sex\" value=\"");
      out.print( sex );
      out.write("\"></td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  \t<tr>\r\n");
      out.write("\t\t\t\t<td>Date of Birth</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"dob\" value=\"");
      out.print( dob );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Address</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"address\" value=\"");
      out.print( address );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Pincode</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"pincode\" value=\"");
      out.print( pincode );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Contact Number</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"phone\" value=\"");
      out.print( phone );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Years of Experience</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"exp\" value=\"");
      out.print( exp );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Highest Educational Attainment</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"degree\" value=\"");
      out.print( degree );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Stream</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"stream\" value=\"");
      out.print( stream );
      out.write("\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<input type=\"submit\" name=\"submit\" id=\"submit\" value=\"Update\" style=\"margin: 0 auto;\">\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<div id=\"cv\">\r\n");
      out.write("\t<form action=\"UploadResume\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t<input name=\"resume\" type=\"file\" />&emsp;\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Add Resume\" />\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br><br>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"My Applications\" align=\"center\" class=\"tabcontent\">\r\n");

	int job_id=0;
	int app_id = 0;
	String name = null;
	String post = null;
	String location = null;

      out.write("\r\n");
      out.write("\r\n");
  
	try{
		ps = con.prepareStatement("SELECT a.app_id, a.job_id, r.name, j.post, j.location FROM applist a, joblist j, recruiterProfile r WHERE a.email=? AND a.job_id=j.job_id AND j.email=r.email;");
		ps.setString(1, email);
		rs = ps.executeQuery();

      out.write("\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("\t<table class=\"table1\" style=\"width:800px;\" align=\"center\" border=\"none\" cellpadding=\"4\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<th class=\"th1\">Application #ID</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Job #ID</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Organization</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Designation</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Location</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Action</th>\r\n");
      out.write("\t\t</thead>\r\n");

		while(rs.next()){
			app_id = rs.getInt("a.app_id");
			job_id = rs.getInt("a.job_id");
			name = rs.getString("r.name");
			post = rs.getString("j.post");
			location = rs.getString("j.location");	

      out.write("\r\n");
      out.write("\t\t<tr class=\"tr1\">\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(app_id);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(job_id);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(name);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(post);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(location);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">\r\n");
      out.write("\t\t\t\t<input type=\"button\" id=\"");
      out.print( -job_id );
      out.write("\" class=\"undo\" value=\"Undo\" onclick=\"location.href='Candidate.jsp'; undo(this.id);\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");

		}
	}
	catch(Exception e){
		e.printStackTrace();
	}

      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"Change Password\" class=\"tabcontent\">\r\n");
      out.write("\t<form name=\"changePassword\" action=\"ChangePassword\"><br><br><br><br>\r\n");
      out.write("\t\t<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write("\t\t\t<tbody>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>Old Password</td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"oldPassword\" placeholder=\"Enter Old Password\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>New Password</td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"newPassword\" placeholder=\"Enter New Password\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>Confirm Password</td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"cnfNewPassword\" placeholder=\"Confirm New Password\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Update\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("  \r\n");
      out.write("<script src=\"JavaScript/TabSwitch.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t<p><font color=\"#505050\" size=\"2\" face=\"Georgia\">&copy; Copyright 2017. All rights reserved.<br>Best viewed on a resolution of 1920 x 1080 on Google Chrome.</font></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
