/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-07-19 20:40:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Homepage.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Header.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"JavaScript/HomepageValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>JobsPikr :: Home Page</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body background=\"Images/HomepageBackground.jpg\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<img class=\"center\" src=\"Images/JobsPikr.png\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- The following section has been made in accordance to steps given at https://www.w3schools.com/howto/howto_js_tabs.asp  -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"loginPane\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"tab\">\r\n");
      out.write("\t\t\t\t<button class=\"tablinks\" onclick=\"openTab(event, 'Candidate')\" id=\"default\">Candidate</button>\r\n");
      out.write("\t\t\t \t<button class=\"tablinks\" onclick=\"openTab(event, 'Recruiter')\"><font>Recruiter</font></button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("  \r\n");
      out.write("\t\t\t<div id=\"Candidate\" class=\"tabcontent\">\r\n");
      out.write("\t\t\t\t<form name=\"candidateLogin\" action=\"CandidateLoginServlet\" method=\"post\" onsubmit=\"return CandidateValidator();\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t    <input type=\"text\" name=\"emailC\" placeholder=\"E-mail\">\r\n");
      out.write("\t\t\t\t    <input type=\"password\" name=\"passwordC\" id=\"passwordC\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t    <input type=\"checkbox\" onchange=\"document.getElementById('passwordC').type = this.checked ? 'text' : 'password'\"> Show password<br>\r\n");
      out.write("\t\t\t\t    <input type=\"submit\" value=\"Login\" />\r\n");
      out.write("\t\t\t\t</form><br>\r\n");
      out.write("\t\t\t\t<p>New to our web site?&emsp;<a href=\"CandidateRegistration.jsp\"style=\"text-decoration: none;\">Register here.</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"Recruiter\" class=\"tabcontent\">\r\n");
      out.write("\t\t\t\t<form name=\"recruiterLogin\" action=\"RecruiterLoginServlet\" method=\"post\" onsubmit=\"return RecruiterValidator();\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"emailR\" placeholder=\"E-mail\">\r\n");
      out.write("\t\t\t\t    <input type=\"password\" name=\"passwordR\" id=\"passwordR\" placeholder=\"Password\">\r\n");
      out.write("\t\t\t\t    <input type=\"checkbox\" onchange=\"document.getElementById('passwordR').type = this.checked ? 'text' : 'password'\"> Show password<br>\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Login\">\r\n");
      out.write("\t\t\t\t</form><br>\r\n");
      out.write("\t\t\t\t<p>New to our web site?&emsp;<a href=\"RecruiterRegistration.jsp\" style=\"text-decoration: none;\">Register here.</a></p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div> <!-- End of div #loginpane -->\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"footer\">\r\n");
      out.write("\t<p><font color=\"#505050\" size=\"2\" face=\"Georgia\">&copy; Copyright 2017. All rights reserved.<br>Best viewed on a resolution of 1920 x 1080 on Google Chrome.</font></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"JavaScript/TabSwitch.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
