/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-07-20 09:45:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Recruiter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Profile.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/Tables.css\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write(".welcome{\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("\tbackground-color: inherit;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-right: 35px;\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction RegValidator()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar email1 = document.RecruiterProfile.email.value;\r\n");
      out.write("\t\tvar name1 = document.RecruiterProfile.name.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar address1 = document.RecruiterProfile.address.value;\r\n");
      out.write("\t\tvar pincode1 = document.RecruiterProfile.pincode.value;\r\n");
      out.write("\t\tvar phone1 = document.RecruiterProfile.phone.value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar website1 = document.RecruiterProfile.website.value;\r\n");
      out.write("\t\tvar validemail = /[a-zA-Z0-9._-]+[@]{1}[a-z]+[.]{1}[a-zA-Z]{3}$/;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(email1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter email\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!(validemail.test(email1)))\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"email not correct\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(name1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter fname\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(address1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter address\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(pincode1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter pincode\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(phone1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter phone\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(website1 == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"Enter Website\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 		
	Connection con = null;
	PreparedStatement ps = null;
	ResultSet rs = null;
	
	try{
		Class.forName("com.mysql.jdbc.Driver");
		con = DriverManager.getConnection("jdbc:mysql://localhost:3306/GlobsynST17ProjectDB", "abhishekp03", "d!ve!nnow");
	}
	catch(Exception e){
		e.printStackTrace();
	}
	
	int status=-1;
	session = request.getSession(false);
	Object ob = session.getAttribute("key");
	Object ob2 = session.getAttribute("key2");
	String email = ob.toString();
	//out.println(email);
	String foo = ob2.toString();
	status = Integer.parseInt(foo);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\" >\r\n");
      out.write("\t<img class=\"center\" src=\"Images/JobsPikr.png\">\r\n");
      out.write("\t<div class=\"welcome\">\r\n");
      out.write("\t\t<p><font color=\"white\"><br>Welcome<br>");
      out.print(email);
      out.write("</font></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"tab\">\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Home')\" id=\"default\">Home</button>\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Edit Profile')\">Edit Profile</button>\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Jobs Published')\">Jobs Published</button>\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Add Job')\">Add Job</button>\r\n");
      out.write("  <button class=\"tablinks\" onclick=\"openTab(event, 'Change Password')\">Change Password</button>\r\n");
      out.write("  <form action=\"Logout\" method=\"post\">\r\n");
      out.write("  \t<button class=\"tablinks\">Logout</button>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Home\" class=\"tabcontent\">\r\n");

	if(status==0){ 

      out.write("\r\n");
      out.write("\r\n");
      out.write("  <h3>Welcome</h3>\r\n");
      out.write("  <h3>You have been successfully register</h3>\r\n");
      out.write("  <p>Create your profile first</p>\r\n");
      out.write("  <input type=\"button\" onclick=\"openTab(event, 'Edit Profile')\" value=\"Create Profile\">\r\n");
      out.write("\r\n");
 
	}
	else{
		int app_id = 0;
		int job_id = 0;
		String fname = null;
		String lname = null;
		String name = null;
		String degree = null;
		String stream = null;
		String qualification = null;
		String exp = null;

		try{
			ps = con.prepareStatement("SELECT a.app_id, a.job_id, c.fname, c.lname, c.degree, c.stream, c.exp FROM applist a, candidateProfile c, recruiterProfile r WHERE a.email=c.email and r.email=?;");
			ps.setString(1, email);
			rs = ps.executeQuery(); 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table class=\"table1\" align=\"center\" border=\"none\" cellpadding=\"5\" style=\"min-width: 700px;\">\r\n");
      out.write("\t\t<br><br><br><br>\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<th class=\"th1\">Application #ID</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Job #ID</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Name</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Qualification</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Experience</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Action</th>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t\t\t\r\n");
 		
			while(rs.next()){
				app_id = rs.getInt("a.app_id");
				job_id = rs.getInt("a.job_id");
				fname = rs.getString("c.fname");
				lname = rs.getString("c.lname");
				name = fname + " " + lname;
				degree = rs.getString("c.degree");
				stream = rs.getString("c.stream");
				qualification = degree + " in " + stream;
				exp = rs.getString("c.exp"); 
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<tr class=\"tr1\">\r\n");
      out.write("\t\t\t\t<td class=\"td1\">");
      out.print(app_id);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"td1\">");
      out.print(job_id);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"td1\">");
      out.print(name);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"td1\">");
      out.print(qualification);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"td1\">");
      out.print(exp);
      out.write("</td>\r\n");
      out.write("\t\t\t\t<td class=\"td1\">\r\n");
      out.write("\t\t\t\t\t<a target=\"_blank\" id=\"");
      out.print(app_id );
      out.write("\" href=\"ViewProfile.jsp?id=");
      out.print(app_id );
      out.write("\" style=\"text-decoration: none;\">View Profile</a>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\t\r\n");
      out.write("\r\n");
 
			}
		}
		catch(Exception e){
			e.printStackTrace();
		}

      out.write("\r\n");
      out.write("\t</table>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"Edit Profile\" class=\"tabcontent\" align=\"center\">\r\n");
	
	String name = "";
	String address = "";
	String pincode = "";
	String phone = "";
	String website = "";

	if(status!=0){
		try{
			ps = con.prepareStatement("SELECT name, address, pincode, phone, website FROM recruiterProfile WHERE email=?;");
			ps.setString(1, email);
			rs=ps.executeQuery();
			while(rs.next()){
				name = rs.getString("name");
				address = rs.getString("address");
				pincode = Long.toString(rs.getLong("pincode"));
				phone = Long.toString(rs.getLong("phone"));
				website = rs.getString("website");
			}
			rs = ps.executeQuery();
			}
		catch(Exception e){
			e.printStackTrace();
		}
	}

      out.write("\r\n");
      out.write("\t<form name=\"RecruiterProfile\" action=\"UpdateRecruiterServlet\" method=\"post\" onsubmit=\"return RegValidator();\">\r\n");
      out.write(" \t\t <table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write(" \t\t <br><br><br><br>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td>E-mail</td>\r\n");
      out.write("\t\t\t      <td><input type=\"text\" name=\"email\"  value=\"");
      out.print( email );
      out.write("\" readonly></td>\r\n");
      out.write("\t\t        </tr>\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td>Name of Organization</td>\r\n");
      out.write("\t\t\t      <td><input type=\"text\" name=\"name\" value=\"");
      out.print( name );
      out.write("\"></td>\r\n");
      out.write("\t\t        </tr>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td>Address</td>\r\n");
      out.write("\t\t\t      <td><input type=\"text\" name=\"address\" value=\"");
      out.print( address );
      out.write("\"></td>\r\n");
      out.write("\t\t        </tr>\r\n");
      out.write("\t\t        \r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td>Pin code</td>\r\n");
      out.write("\t\t\t      <td><input type=\"text\" name=\"pincode\" value=\"");
      out.print( pincode );
      out.write("\"></td>\r\n");
      out.write("\t\t        </tr>\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t  \t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Contact Number</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"phone\" value=\"");
      out.print( phone );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Website</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"website\" value=\"");
      out.print( website );
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"submit\" name=\"submit\" id=\"submit\" value=\"Update\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("        \t</tbody>\r\n");
      out.write("\t \t </table> \r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"Jobs Published\" class=\"tabcontent\" align=\"center\">\r\n");

	int job_id = 0;
	String post = null;
	String location = null;
	String salary = null;
	String exp = null;
	String description = null;
	
	try{
		ps = con.prepareStatement("SELECT * FROM joblist WHERE email=?;");
		ps.setString(1, email);
		rs = ps.executeQuery();

      out.write("\r\n");
      out.write("\t<br><br><br><br>\r\n");
      out.write("\t<table class=\"table1\" align=\"center\" border=\"none\" cellpadding=\"4\" style=\"min-width:800px;\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<th class=\"th1\">Job #ID</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Designation</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Location</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Salary</th>\r\n");
      out.write("\t\t\t<th class=\"th1\">Experience</th>\r\n");
      out.write("\t\t    <th class=\"th1\">Job Description</th>\r\n");
      out.write("\t\t    <th class=\"th1\">Action</th>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t\r\n");
 
		while(rs.next()){
			job_id = rs.getInt("job_id");
			post = rs.getString("post");
			location = rs.getString("location");
			salary = rs.getString("salary");
			exp = rs.getString("exp");
			description = rs.getString("description");

      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("        <tr class=\"tr1\">\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(job_id);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(post);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(location);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(salary);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(exp);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\">");
      out.print(description);
      out.write("</td>\r\n");
      out.write("\t\t\t<td class=\"td1\"><a href=\"\" style=\"text-decoration:none;\">Delete</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t\r\n");

		}
	}
	catch(Exception e){
		e.printStackTrace();
	}

      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"Add Job\" class=\"tabcontent\" align=\"center\">\t\r\n");
      out.write("\t<form name=\"addjob\" action=\"AddJobServlet\" method=\"post\">\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t<br><br><br><br>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Email : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"email\" value=\"");
      out.print(email);
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Post : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"post\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Location : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"location\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Salary : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"salary\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Experience : </td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"exp\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Description</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"desc\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" value=\"Add Job\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"Change Password\" class=\"tabcontent\">\r\n");
      out.write("\t<form name=\"changePassword\" action=\"ChangePassword\"><br><br><br><br>\r\n");
      out.write("\t\t<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"5\" cellspacing=\"5\">\r\n");
      out.write("\t\t\t<tbody>\t\t\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>Old Password</td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"oldPassword\" placeholder=\"Enter Old Password\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>New Password</td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"newPassword\" placeholder=\"Enter New Password\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t<td>Confirm Password</td>\r\n");
      out.write("\t\t\t<td><input type=\"password\" name=\"cnfNewPassword\" placeholder=\"Confirm New Password\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"Update\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"JavaScript/TabSwitch.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t<p><font color=\"#505050\" size=\"2\" face=\"Georgia\">&copy; Copyright 2017. All rights reserved.<br>Best viewed on a resolution of 1920 x 1080 on Google Chrome.</font></p>\r\n");
      out.write("</div>\r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
