/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-07-20 07:02:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.*;

public final class ViewProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/Header.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("    font-family: arial, sans-serif;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    table-layout: fixed;\r\n");
      out.write("    width: auto;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("td, th {\r\n");
      out.write("    border: 1px solid black;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("th {\r\n");
      out.write("\tbackground-color: #C8D6A2;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("tr:nth-child(even) {\r\n");
      out.write("    background-color: #dddddd;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<title>Profile</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<img class=\"center\" src=\"Images/JobsPikr.png\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"main\" style=\"min-height: 650px; text-align:center\">\r\n");
      out.write("\r\n");
 
int app_id = Integer.parseInt(request.getParameter("id"));
String fname = null;
String lname = null;
String name = null;
String degree = null;
String stream = null;
String qualification=null;
String exp = null;
String email = null;
Long phone = 0L;

try{
	Class.forName("com.mysql.jdbc.Driver");
	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/GlobsynST17ProjectDB", "abhishekp03", "d!ve!nnow");
	PreparedStatement ps = con.prepareStatement("SELECT c.fname, c.lname, c.degree, c.stream, c.exp, c.email, c.phone FROM applist a, candidateProfile c WHERE a.app_id=? and a.email=c.email;");
	ps.setInt(1, app_id);
	ResultSet rs = ps.executeQuery();
	while(rs.next()){
		fname = rs.getString("c.fname");
		lname = rs.getString("c.lname");
		name = fname + " " + lname;
		degree = rs.getString("c.degree");
		stream = rs.getString("c.stream");
		qualification = degree + " in " + stream;
		exp = rs.getString("c.exp");
		email = rs.getString("c.email");
		phone = rs.getLong("c.phone");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"picture\" style=\"margin:0 auto; text-align:center;\">\r\n");
      out.write("\t<img src=\"ViewImage.jsp?name=");
      out.print(email );
      out.write("\" />\r\n");
      out.write("</div><br><br>\r\n");
      out.write("\r\n");
      out.write("<a target=\"_blank\" href=\"ViewResume.jsp?name=");
      out.print(email );
      out.write("\" style=\"text-decoration: none;\">View Resume</a>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("<table width=\"400px\" align=\"center\" cellspacing=\"0px\" cellpadding=\"5px\">\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Name: </td>\r\n");
      out.write("\t<td>");
      out.print(name);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Highest Educational Attainment: </td>\r\n");
      out.write("\t<td>");
      out.print(qualification);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Experience: </td>\r\n");
      out.write("\t<td>");
      out.print(exp);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Email: </td>\r\n");
      out.write("\t<td>");
      out.print(email);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>Phone: </td>\r\n");
      out.write("\t<td>");
      out.print(phone);
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<a id=\"");
      out.print(app_id );
      out.write("\" href=\"CallUp.jsp?id=");
      out.print(app_id);
      out.write("\"style=\"text-decoration:none;\">Call For Interview</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("\t<td>\r\n");
      out.write("\t\t<a id=\"");
      out.print(app_id );
      out.write("\" href=\"Recruiter.jsp\" style=\"text-decoration:none;\">Ignore Application</a>\r\n");
      out.write("\t</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\t\r\n");

	}//end of while
}//end of try
catch(Exception e){
	e.printStackTrace();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("\t<p><font color=\"#505050\" size=\"2\" face=\"Georgia\">&copy; Copyright 2017. All rights reserved.<br>Best viewed on a resolution of 1920 x 1080 on Google Chrome.</font></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
